name: CI


on:
  workflow_dispatch:

jobs:
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Editar Arquivo
        run: echo ${{ github.sha }} >> file
        
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email noreply@github.com
          git add file
          git commit -m "alterando arquivo atraves do workflow"
          git push
      
      
