name: Create Release
run-name: v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versão  (ie 5.5.0)'
        required: true
      beta:
        description: 'Pre-release? (0 - Stable, 1 - Beta)'
        default: '1'
        required: true
        
permissions:
  contents: write
  
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ toJSON(inputs) }}'
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Atualizar versão
      run: mvn -B build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.incrementalVersion}
    - name: Criar Branch de Release
      run: |
        git checkout -b release/$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git config user.name github-actions
        git config user.email noreply@github.com
        git add *pom.xml
        git commit -m "Release $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        git push origin release/$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - run: mkdir artifacts
    - name: Construir Artefatos
      run: mvn -B package --file pom.xml dependency:copy -Dartifact=\${project.groupId}:\${project.artifactId}:\${project.version} -DoutputDirectory=artifacts    
    - name: Criar Release
      id: create_release
      run: gh release create v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) artifacts/*.jar --title=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) --draft --prerelease
      env: 
        GH_TOKEN: ${{ github.token }}
